version: 2.1
orbs:
  spruce: sprucelabsai/orb@1
jobs:
  test:
    docker:
      - image: cimg/node:lts
      - image: cimg/postgres:14.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: skill-tests
    working_directory: /mnt/ramdisk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ec:9f:2e:aa:1f:c9:ab:49:57:8f:c0:cd:2e:5b:f3:b0"
      - checkout
      - spruce/check_and_skip_if_npm_publish
      - spruce/install_rsync
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Restore DB
          command: |
            sudo apt install postgresql-client
            psql postgres://postgres:password@localhost:5432/skill-tests < src/__tests__/support/reset_dev_database.sql
      - spruce/install_deps_build_ci_test
      - spruce/exit_if_not_auto_upgrade
      - spruce/merge_auto_upgrade
  npm_publish:
    docker:
      - image: cimg/node:lts
    working_directory: /mnt/ramdisk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ec:9f:2e:aa:1f:c9:ab:49:57:8f:c0:cd:2e:5b:f3:b0"
      - checkout
      - spruce/check_and_skip_if_npm_publish
      - spruce/install_rsync
      - spruce/install_deps_build_dist_release
  upgrade:
    docker:
      - image: cimg/node:lts
    working_directory: /mnt/ramdisk
    steps:
      - spruce/check_for_autoupgrade_dns
      - add_ssh_keys:
          fingerprints:
            - "ec:9f:2e:aa:1f:c9:ab:49:57:8f:c0:cd:2e:5b:f3:b0"
      - spruce/check_for_ssh_keys_env
      - spruce/setup_ct_npm_cache
      - checkout
      - spruce/set_target_branch_env
      - spruce/install_rsync
      - spruce/install_cli
      - spruce/upgrade_check_for_major
      - spruce/check_for_newline_only_diff
      - spruce/create_pr
workflows:
  version: 2.1
  do_build:
    jobs:
      - test:
          context: public_package_publish
      - npm_publish:
          requires:
            - test
          context: public_package_publish
          filters:
            branches:
              only:
                - master
  upgrade:
    jobs:
      - upgrade:
          context: public_package_publish
          filters:
            branches:
              only:
                - never_run_only_for_cron
